# Recurso do K8s, para configurar como e o que subir no POD.
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  labels:
    app: redis
# Confs do meu Deployment
spec:
# Precisamos dele para que o service possa ser linkado.
  selector:
    matchLabels: # Dados de identificação no K8s
      app: redis
  replicas: 1
  template:
    metadata:
      labels:
        app: redis
# Confs do meu container no POD.
    spec:
      containers:
      - name: bookshop-redis
        image: redis:6
        ports:
        - containerPort: 6379
        command: ["redis-server"]
        args: ["--requirepass", "T5r4e3t1ps9!"]

---
# O Recurso no qual o K8s te dá, para que você acesse um POD, já que não vai conseguir acessá-lo diretamente.
apiVersion: v1
kind: Service
metadata:
  name: redis-service
  labels:
    app: redis-service
    role: master
spec:
  ports:
  - port: 6379
    targetPort: 6379
  # É esse cara que linka o Service ao POD.
  selector:
    app: redis
