version: '3'
networks: 
    api_network:
volumes:
    mongo_data:
    # https://docs.docker.com/storage/volumes/
services:
    db:
    # https://hub.docker.com/_/mongo
        container_name: mongodb
        image: mongo:4.4.0-bionic
        volumes: 
            - mongo_data:/data/db
        restart: always
        
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: T5r4e3t1ps9
        ports:
            - "5010:27017"

        networks: 
          -  api_network
    rabbit:
        image: rabbitmq:3-management
        environment:
            RABBITMQ_ERLANG_COOKIE: "OJSJBREFSGCJXBXEDJAL"
            RABBITMQ_DEFAULT_USER: "wy7"
            RABBITMQ_DEFAULT_PASS: "rabbitmq"
            RABBITMQ_DEFAULT_VHOST: "/"
        ports:
          -  "15672:15672"
          -  "5672:5672"
    reddis:
        image: redis:6
        command: redis-server --requirepass T5r4e3t1ps9!
        ports:
          -  "6379:6379"